name: Test with Maven
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      args:
        description: Extra Arguments
        default: test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 16
      uses: actions/setup-java@v3
      with:
        java-version: '16'
        distribution: 'temurin'
        cache: maven
    - name: Test with Maven
      run: mvn test
      if: github.event.inputs.args == ''
    - name: Test with Maven (Extra Arguments)
      run: mvn ${{ github.event.inputs.args }}
      if: github.event.inputs.args != ''
