name: Maven
on:
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "microsoft"
          cache: "maven"
      - name: Maven (test)
        run: mvn test